import Head from 'next/head'
import Layout from '../src/components/Layout'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Alternativa 19 del Sur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ADS--LOGO_AZUL.ico" />
      </Head>
      
    </Layout>
  )
}
